- name: Setup Node.js and Express app
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Node.js and NPM
      ansible.builtin.apt:
        name: nodejs, npm
        update_cache: yes

    - name: Create application directory
      ansible.builtin.file:
        path: /var/www/src
        state: directory
        owner: your_remote_user
        group: your_remote_user
        mode: '0755'

    - name: Copy application files
      ansible.builtin.copy:
        src: ./src # Path to your local Express app
        dest: /var/www/src
        owner: your_remote_user
        group: your_remote_user

    - name: Install Node.js dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /var/www/src

    - name: Start Express application (e.g., using systemd)
      ansible.builtin.systemd:
        name: your_express_app.service # You'll need to create this service file
        state: started
        enabled: yes